name: roohbaru_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  uuid: ^4.5.1
  video_player: ^2.9.5
  path: ^1.9.0
  path_provider: ^2.1.2
  open_file: ^3.5.10
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  material_symbols_icons: ^4.0.0
  phosphor_flutter: ^1.0.0
  flutter_svg: ^2.1.0
  flutter_image_compress: ^2.4.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  alchemist: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
    - assets/videos/
    - assets/fonts/
    - assets/icons/pencil-simple-slash.svg
    - assets/icons/mood.svg
  
  fonts:
    - family: lufga-medium
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-medium.otf
    - family: lufga-light
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-light.otf
    - family: lufga-bold
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-bold.otf
    - family: lufga-regular
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-regular.otf
    - family: lufga-light-italic
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-lightitalic.otf
    - family: lufga-semi-bold
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-semibold.otf
    - family: lufga-semi-bold-italic
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-semibolditalic.otf
    - family: lufga-extra-light
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-extralight.otf
    - family: lufga-bold-italic
      fonts:
        - asset: assets/fonts/lufga/Fontspring-DEMO-lufga-bolditalic.otf