// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3z_PSL22umx_S0aY-LJHASdTFHqAg6hE',
    appId: '1:718658476081:web:89b9914e9a4ce6be5fdd10',
    messagingSenderId: '718658476081',
    projectId: 'roohbaru-28a4d',
    authDomain: 'roohbaru-28a4d.firebaseapp.com',
    storageBucket: 'roohbaru-28a4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRIJA6-6Z6oBByvH5l6o0nuYT3JI2suec',
    appId: '1:718658476081:android:d4e53c62222b76f35fdd10',
    messagingSenderId: '718658476081',
    projectId: 'roohbaru-28a4d',
    storageBucket: 'roohbaru-28a4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63RkspFTXHAP-kPOoUnR-KyFstVatDwM',
    appId: '1:718658476081:ios:5c11a060a59df5295fdd10',
    messagingSenderId: '718658476081',
    projectId: 'roohbaru-28a4d',
    storageBucket: 'roohbaru-28a4d.firebasestorage.app',
    androidClientId: '718658476081-9eltjruddb5th8fdqrnluni8cdq3c00b.apps.googleusercontent.com',
    iosClientId: '718658476081-i3sqtfc1qjcaq9td5jbqj0u6142imq8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.roohbaruApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA63RkspFTXHAP-kPOoUnR-KyFstVatDwM',
    appId: '1:718658476081:ios:5c11a060a59df5295fdd10',
    messagingSenderId: '718658476081',
    projectId: 'roohbaru-28a4d',
    storageBucket: 'roohbaru-28a4d.firebasestorage.app',
    androidClientId: '718658476081-9eltjruddb5th8fdqrnluni8cdq3c00b.apps.googleusercontent.com',
    iosClientId: '718658476081-i3sqtfc1qjcaq9td5jbqj0u6142imq8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.roohbaruApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3z_PSL22umx_S0aY-LJHASdTFHqAg6hE',
    appId: '1:718658476081:web:9c8d38ce6ea757ad5fdd10',
    messagingSenderId: '718658476081',
    projectId: 'roohbaru-28a4d',
    authDomain: 'roohbaru-28a4d.firebaseapp.com',
    storageBucket: 'roohbaru-28a4d.firebasestorage.app',
  );
}
